var userBtn = document.querySelector('#btn-user');
var nameInputEl = document.querySelector('#cityname');
var liContainer = document.querySelector('#card-search');
var cityForm = document.querySelector('#cityForm');
var cityContainer = document.querySelector('#city-container');
var fivedayEl =document.querySelector('#fiveday-header');
var dayForecast = document.querySelector('#day-forecast');
var APIKey= "c34e5300156b6ed973d2421c25421b56";
let searchHistory = JSON.parse(localStorage.getItem("search")) || [];
citySearch();
